import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Inter_Tight, Cabin, Lexend_Deca } from "next/font/google";
import { CartSection } from "@/shared/components/cart-section/CartSection";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
});
const cabin = Cabin({ subsets: ["latin"], variable: "--font-cabin" });
const lexend = Lexend_Deca({ subsets: ["latin"], variable: "--font-lexend" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${interTight.variable} ${cabin.variable} ${lexend.variable}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center h-dvh">
          <div className="flex w-full justify-center">{children}</div>
        </div>
        <CartSection />
      </body>
    </html>
  );
}
